### ISSUE TITLE
Issue with application/xml typed contents parsing

### ISSUE THREAD

**Issue by hettmett** [akornatskyy/wheezy.http#3]
### Issue

In case of `application/xml` typed contents we encounter the issue in request body parsing routines. The conflicting situation is appeared because of the way `wsgi.input` is parsed.
In `load_body` function of the `HTTPRequest` class body parsers are mapped by the short-cuts that are not unique. Defined mappings are the following:

`application/x-www-form-urlencoded -> '/x'`
`application/json -> '/j'`
`multipart/form-data -> 'm' (actually starts with 'm')`

In case of the `application/xml` typed content it's matched by `'/x'` pattern and parsed as `x-www-form-urlencoded`, which is not correct. We have bypassed this issue by parsing the `wsgi.input` "manually", but we would like avoid the situations like this.

### Suggested solutions:

- To avoid non-unique mapping definition let's use full name or more characters (if you think full string comparison will affect performance) of content types. This will not help us to avoid "manual" parsing of `wsgi.input`, but at least the inaccurate parsing will not take place.

- To go further we could parse XML typed contents as well, by using defusedxml [https://pypi.org/project/defusedxml/] library to avoid some of the well known XML vulnerabilities. This solution needs further discussion cause storing XML tag attributes in dict has many non-standardized ways and we can avoid XML parsing at all.

**Comment by akornatskyy** [comment]
The use of full name or more characters for content type matching doesn't solve the problem, you will get `(None, None)` in response.

Do not use `req.form`, `req.files`, `req.load_body()` for XML content type... the library doesn't provide a capability to process XML.

You can use `req.stream` instead (which is `wsgi.input` in fact) and pass it as an input into XML parsing code, for example:

```python
from defusedxml.ElementTree import parse

# ...
if 'xml' not in req.content_type:
  # TODO: 
  return
xml = parse(req.stream)  
```
