### ISSUE TITLE
Deprecation of CGI module

### ISSUE THREAD

**Issue by vladimir-poghosyan** [akornatskyy/wheezy.http#30]
If I am not mistaken **wheezy.http** relies on _cgi.FieldStorage_ for parsing multipart form data. The acceptance of the [PEP-594](https://peps.python.org/pep-0594/) marked it (and many other modules from standard library) as deprecated and to be removed in Python 3.13. Although Python 3.11 has just been released and 3.13 won't be released earlier than the end of 2024, personally I think that the deprecation issue should be addressed.

Maybe something like [multipart](https://github.com/defnull/multipart) can be used as a replacement for the FieldStorage?

Thanks.

**Comment by akornatskyy** [comment]
deprecation notes suggest multipart package. it needs to be evaluated as a potential replacement for the `FieldStorage`.

**Comment by vladimir-poghosyan** [comment]
With the [release of Python 3.13](https://pythoninsider.blogspot.com/2024/10/python-3130-final-released.html) this issue becomes blocker for future upgrades. Do you think we can have any updates on this?

**Comment by akornatskyy** [comment]
yes; just need to see which options we have as of today.

**Comment by vladimir-poghosyan** [comment]
Interesting solution. I tried `3.2.1` and everything worked as expected. Thank you!
