### ISSUE TITLE
Missing SameSite attribute for cookies

### ISSUE THREAD

**Issue by vladimir-poghosyan** [akornatskyy/wheezy.http#5]
It seems that `HTTPCookie` class doesn't implement cookies with `SameSite` attribute. I understand that it is possible to extend the `HTTPCookie` class and add support for the attribute. But since all major browsers support `SameSite` cookies, I think it would be nice to have a built-in functionality for them.

Thanks.

**Comment by akornatskyy** [comment]
Added in version 0.1.358

**Comment by vladimir-poghosyan** [comment]
Great! Already tried it.
Thank You.
